export interface Country {
  title: string;
  phoneCode: string;
  currencyCode: string;
  countryCode: string;
}

export const countries: Country[] = [
  { title: "Afghanistan", phoneCode: "+93", currencyCode: "AFN", countryCode: "AF" },
  { title: "Albania", phoneCode: "+355", currencyCode: "ALL", countryCode: "AL" },
  { title: "Algeria", phoneCode: "+213", currencyCode: "DZD", countryCode: "DZ" },
  { title: "Andorra", phoneCode: "+376", currencyCode: "EUR", countryCode: "AD" },
  { title: "Angola", phoneCode: "+244", currencyCode: "AOA", countryCode: "AO" },
  { title: "Antigua and Barbuda", phoneCode: "+1-268", currencyCode: "XCD", countryCode: "AG" },
  { title: "Argentina", phoneCode: "+54", currencyCode: "ARS", countryCode: "AR" },
  { title: "Armenia", phoneCode: "+374", currencyCode: "AMD", countryCode: "AM" },
  { title: "Australia", phoneCode: "+61", currencyCode: "AUD", countryCode: "AU" },
  { title: "Austria", phoneCode: "+43", currencyCode: "EUR", countryCode: "AT" },
  { title: "Azerbaijan", phoneCode: "+994", currencyCode: "AZN", countryCode: "AZ" },
  { title: "Bahamas", phoneCode: "+1-242", currencyCode: "BSD", countryCode: "BS" },
  { title: "Bahrain", phoneCode: "+973", currencyCode: "BHD", countryCode: "BH" },
  { title: "Bangladesh", phoneCode: "+880", currencyCode: "BDT", countryCode: "BD" },
  { title: "Barbados", phoneCode: "+1-246", currencyCode: "BBD", countryCode: "BB" },
  { title: "Belarus", phoneCode: "+375", currencyCode: "BYN", countryCode: "BY" },
  { title: "Belgium", phoneCode: "+32", currencyCode: "EUR", countryCode: "BE" },
  { title: "Belize", phoneCode: "+501", currencyCode: "BZD", countryCode: "BZ" },
  { title: "Benin", phoneCode: "+229", currencyCode: "XOF", countryCode: "BJ" },
  { title: "Bhutan", phoneCode: "+975", currencyCode: "BTN", countryCode: "BT" },
  { title: "Bolivia", phoneCode: "+591", currencyCode: "BOB", countryCode: "BO" },
  { title: "Bosnia and Herzegovina", phoneCode: "+387", currencyCode: "BAM", countryCode: "BA" },
  { title: "Botswana", phoneCode: "+267", currencyCode: "BWP", countryCode: "BW" },
  { title: "Brazil", phoneCode: "+55", currencyCode: "BRL", countryCode: "BR" },
  { title: "Brunei", phoneCode: "+673", currencyCode: "BND", countryCode: "BN" },
  { title: "Bulgaria", phoneCode: "+359", currencyCode: "BGN", countryCode: "BG" },
  { title: "Burkina Faso", phoneCode: "+226", currencyCode: "XOF", countryCode: "BF" },
  { title: "Burundi", phoneCode: "+257", currencyCode: "BIF", countryCode: "BI" },
  { title: "Cabo Verde", phoneCode: "+238", currencyCode: "CVE", countryCode: "CV" },
  { title: "Cambodia", phoneCode: "+855", currencyCode: "KHR", countryCode: "KH" },
  { title: "Cameroon", phoneCode: "+237", currencyCode: "XAF", countryCode: "CM" },
  { title: "Canada", phoneCode: "+1", currencyCode: "CAD", countryCode: "CA" },
  { title: "Central African Republic", phoneCode: "+236", currencyCode: "XAF", countryCode: "CF" },
  { title: "Chad", phoneCode: "+235", currencyCode: "XAF", countryCode: "TD" },
  { title: "Chile", phoneCode: "+56", currencyCode: "CLP", countryCode: "CL" },
  { title: "China", phoneCode: "+86", currencyCode: "CNY", countryCode: "CN" },
  { title: "Colombia", phoneCode: "+57", currencyCode: "COP", countryCode: "CO" },
  { title: "Comoros", phoneCode: "+269", currencyCode: "KMF", countryCode: "KM" },
  { title: "Congo (DRC)", phoneCode: "+243", currencyCode: "CDF", countryCode: "CD" },
  { title: "Congo (Republic)", phoneCode: "+242", currencyCode: "XAF", countryCode: "CG" },
  { title: "Costa Rica", phoneCode: "+506", currencyCode: "CRC", countryCode: "CR" },
  { title: "Croatia", phoneCode: "+385", currencyCode: "EUR", countryCode: "HR" },
  { title: "Cuba", phoneCode: "+53", currencyCode: "CUP", countryCode: "CU" },
  { title: "Cyprus", phoneCode: "+357", currencyCode: "EUR", countryCode: "CY" },
  { title: "Czech Republic", phoneCode: "+420", currencyCode: "CZK", countryCode: "CZ" },
  { title: "Denmark", phoneCode: "+45", currencyCode: "DKK", countryCode: "DK" },
  { title: "Djibouti", phoneCode: "+253", currencyCode: "DJF", countryCode: "DJ" },
  { title: "Dominica", phoneCode: "+1-767", currencyCode: "XCD", countryCode: "DM" },
  { title: "Dominican Republic", phoneCode: "+1-809", currencyCode: "DOP", countryCode: "DO" },
  { title: "Ecuador", phoneCode: "+593", currencyCode: "USD", countryCode: "EC" },
  { title: "Egypt", phoneCode: "+20", currencyCode: "EGP", countryCode: "EG" },
  { title: "El Salvador", phoneCode: "+503", currencyCode: "USD", countryCode: "SV" },
  { title: "Equatorial Guinea", phoneCode: "+240", currencyCode: "XAF", countryCode: "GQ" },
  { title: "Eritrea", phoneCode: "+291", currencyCode: "ERN", countryCode: "ER" },
  { title: "Estonia", phoneCode: "+372", currencyCode: "EUR", countryCode: "EE" },
  { title: "Eswatini", phoneCode: "+268", currencyCode: "SZL", countryCode: "SZ" },
  { title: "Ethiopia", phoneCode: "+251", currencyCode: "ETB", countryCode: "ET" },
  { title: "Fiji", phoneCode: "+679", currencyCode: "FJD", countryCode: "FJ" },
  { title: "Finland", phoneCode: "+358", currencyCode: "EUR", countryCode: "FI" },
  { title: "France", phoneCode: "+33", currencyCode: "EUR", countryCode: "FR" },
  { title: "Gabon", phoneCode: "+241", currencyCode: "XAF", countryCode: "GA" },
  { title: "Gambia", phoneCode: "+220", currencyCode: "GMD", countryCode: "GM" },
  { title: "Georgia", phoneCode: "+995", currencyCode: "GEL", countryCode: "GE" },
  { title: "Germany", phoneCode: "+49", currencyCode: "EUR", countryCode: "DE" },
  { title: "Ghana", phoneCode: "+233", currencyCode: "GHS", countryCode: "GH" },
  { title: "Greece", phoneCode: "+30", currencyCode: "EUR", countryCode: "GR" },
  { title: "Grenada", phoneCode: "+1-473", currencyCode: "XCD", countryCode: "GD" },
  { title: "Guatemala", phoneCode: "+502", currencyCode: "GTQ", countryCode: "GT" },
  { title: "Guinea", phoneCode: "+224", currencyCode: "GNF", countryCode: "GN" },
  { title: "Guinea-Bissau", phoneCode: "+245", currencyCode: "XOF", countryCode: "GW" },
  { title: "Guyana", phoneCode: "+592", currencyCode: "GYD", countryCode: "GY" },
  { title: "Haiti", phoneCode: "+509", currencyCode: "HTG", countryCode: "HT" },
  { title: "Honduras", phoneCode: "+504", currencyCode: "HNL", countryCode: "HN" },
  { title: "Hungary", phoneCode: "+36", currencyCode: "HUF", countryCode: "HU" },
  { title: "Iceland", phoneCode: "+354", currencyCode: "ISK", countryCode: "IS" },
  { title: "India", phoneCode: "+91", currencyCode: "INR", countryCode: "IN" },
  { title: "Indonesia", phoneCode: "+62", currencyCode: "IDR", countryCode: "ID" },
  { title: "Iran", phoneCode: "+98", currencyCode: "IRR", countryCode: "IR" },
  { title: "Iraq", phoneCode: "+964", currencyCode: "IQD", countryCode: "IQ" },
  { title: "Ireland", phoneCode: "+353", currencyCode: "EUR", countryCode: "IE" },
  { title: "Israel", phoneCode: "+972", currencyCode: "ILS", countryCode: "IL" },
  { title: "Italy", phoneCode: "+39", currencyCode: "EUR", countryCode: "IT" },
  { title: "Ivory Coast", phoneCode: "+225", currencyCode: "XOF", countryCode: "CI" },
  { title: "Jamaica", phoneCode: "+1-876", currencyCode: "JMD", countryCode: "JM" },
  { title: "Japan", phoneCode: "+81", currencyCode: "JPY", countryCode: "JP" },
  { title: "Jordan", phoneCode: "+962", currencyCode: "JOD", countryCode: "JO" },
  { title: "Kazakhstan", phoneCode: "+7", currencyCode: "KZT", countryCode: "KZ" },
  { title: "Kenya", phoneCode: "+254", currencyCode: "KES", countryCode: "KE" },
  { title: "Kiribati", phoneCode: "+686", currencyCode: "AUD", countryCode: "KI" },
  { title: "Kosovo", phoneCode: "+383", currencyCode: "EUR", countryCode: "XK" },
  { title: "Kuwait", phoneCode: "+965", currencyCode: "KWD", countryCode: "KW" },
  { title: "Kyrgyzstan", phoneCode: "+996", currencyCode: "KGS", countryCode: "KG" },
  { title: "Laos", phoneCode: "+856", currencyCode: "LAK", countryCode: "LA" },
  { title: "Latvia", phoneCode: "+371", currencyCode: "EUR", countryCode: "LV" },
  { title: "Lebanon", phoneCode: "+961", currencyCode: "LBP", countryCode: "LB" },
  { title: "Lesotho", phoneCode: "+266", currencyCode: "LSL", countryCode: "LS" },
  { title: "Liberia", phoneCode: "+231", currencyCode: "LRD", countryCode: "LR" },
  { title: "Libya", phoneCode: "+218", currencyCode: "LYD", countryCode: "LY" },
  { title: "Liechtenstein", phoneCode: "+423", currencyCode: "CHF", countryCode: "LI" },
  { title: "Lithuania", phoneCode: "+370", currencyCode: "EUR", countryCode: "LT" },
  { title: "Luxembourg", phoneCode: "+352", currencyCode: "EUR", countryCode: "LU" },
  { title: "Madagascar", phoneCode: "+261", currencyCode: "MGA", countryCode: "MG" },
  { title: "Malawi", phoneCode: "+265", currencyCode: "MWK", countryCode: "MW" },
  { title: "Malaysia", phoneCode: "+60", currencyCode: "MYR", countryCode: "MY" },
  { title: "Maldives", phoneCode: "+960", currencyCode: "MVR", countryCode: "MV" },
  { title: "Mali", phoneCode: "+223", currencyCode: "XOF", countryCode: "ML" },
  { title: "Malta", phoneCode: "+356", currencyCode: "EUR", countryCode: "MT" },
  { title: "Marshall Islands", phoneCode: "+692", currencyCode: "USD", countryCode: "MH" },
  { title: "Mauritania", phoneCode: "+222", currencyCode: "MRU", countryCode: "MR" },
  { title: "Mauritius", phoneCode: "+230", currencyCode: "MUR", countryCode: "MU" },
  { title: "Mexico", phoneCode: "+52", currencyCode: "MXN", countryCode: "MX" },
  { title: "Micronesia", phoneCode: "+691", currencyCode: "USD", countryCode: "FM" },
  { title: "Moldova", phoneCode: "+373", currencyCode: "MDL", countryCode: "MD" },
  { title: "Monaco", phoneCode: "+377", currencyCode: "EUR", countryCode: "MC" },
  { title: "Mongolia", phoneCode: "+976", currencyCode: "MNT", countryCode: "MN" },
  { title: "Montenegro", phoneCode: "+382", currencyCode: "EUR", countryCode: "ME" },
  { title: "Morocco", phoneCode: "+212", currencyCode: "MAD", countryCode: "MA" },
  { title: "Mozambique", phoneCode: "+258", currencyCode: "MZN", countryCode: "MZ" },
  { title: "Myanmar", phoneCode: "+95", currencyCode: "MMK", countryCode: "MM" },
  { title: "Namibia", phoneCode: "+264", currencyCode: "NAD", countryCode: "NA" },
  { title: "Nauru", phoneCode: "+674", currencyCode: "AUD", countryCode: "NR" },
  { title: "Nepal", phoneCode: "+977", currencyCode: "NPR", countryCode: "NP" },
  { title: "Netherlands", phoneCode: "+31", currencyCode: "EUR", countryCode: "NL" },
  { title: "New Zealand", phoneCode: "+64", currencyCode: "NZD", countryCode: "NZ" },
  { title: "Nicaragua", phoneCode: "+505", currencyCode: "NIO", countryCode: "NI" },
  { title: "Niger", phoneCode: "+227", currencyCode: "XOF", countryCode: "NE" },
  { title: "Nigeria", phoneCode: "+234", currencyCode: "NGN", countryCode: "NG" },
  { title: "North Korea", phoneCode: "+850", currencyCode: "KPW", countryCode: "KP" },
  { title: "North Macedonia", phoneCode: "+389", currencyCode: "MKD", countryCode: "MK" },
  { title: "Norway", phoneCode: "+47", currencyCode: "NOK", countryCode: "NO" },
  { title: "Oman", phoneCode: "+968", currencyCode: "OMR", countryCode: "OM" },
  { title: "Pakistan", phoneCode: "+92", currencyCode: "PKR", countryCode: "PK" },
  { title: "Palau", phoneCode: "+680", currencyCode: "USD", countryCode: "PW" },
  { title: "Palestine", phoneCode: "+970", currencyCode: "ILS", countryCode: "PS" },
  { title: "Panama", phoneCode: "+507", currencyCode: "PAB", countryCode: "PA" },
  { title: "Papua New Guinea", phoneCode: "+675", currencyCode: "PGK", countryCode: "PG" },
  { title: "Paraguay", phoneCode: "+595", currencyCode: "PYG", countryCode: "PY" },
  { title: "Peru", phoneCode: "+51", currencyCode: "PEN", countryCode: "PE" },
  { title: "Philippines", phoneCode: "+63", currencyCode: "PHP", countryCode: "PH" },
  { title: "Poland", phoneCode: "+48", currencyCode: "PLN", countryCode: "PL" },
  { title: "Portugal", phoneCode: "+351", currencyCode: "EUR", countryCode: "PT" },
  { title: "Qatar", phoneCode: "+974", currencyCode: "QAR", countryCode: "QA" },
  { title: "Romania", phoneCode: "+40", currencyCode: "RON", countryCode: "RO" },
  { title: "Russia", phoneCode: "+7", currencyCode: "RUB", countryCode: "RU" },
  { title: "Rwanda", phoneCode: "+250", currencyCode: "RWF", countryCode: "RW" },
  { title: "Saint Kitts and Nevis", phoneCode: "+1-869", currencyCode: "XCD", countryCode: "KN" },
  { title: "Saint Lucia", phoneCode: "+1-758", currencyCode: "XCD", countryCode: "LC" },
  { title: "Saint Vincent and the Grenadines", phoneCode: "+1-784", currencyCode: "XCD", countryCode: "VC" },
  { title: "Samoa", phoneCode: "+685", currencyCode: "WST", countryCode: "WS" },
  { title: "San Marino", phoneCode: "+378", currencyCode: "EUR", countryCode: "SM" },
  { title: "Sao Tome and Principe", phoneCode: "+239", currencyCode: "STN", countryCode: "ST" },
  { title: "Saudi Arabia", phoneCode: "+966", currencyCode: "SAR", countryCode: "SA" },
  { title: "Senegal", phoneCode: "+221", currencyCode: "XOF", countryCode: "SN" },
  { title: "Serbia", phoneCode: "+381", currencyCode: "RSD", countryCode: "RS" },
  { title: "Seychelles", phoneCode: "+248", currencyCode: "SCR", countryCode: "SC" },
  { title: "Sierra Leone", phoneCode: "+232", currencyCode: "SLL", countryCode: "SL" },
  { title: "Singapore", phoneCode: "+65", currencyCode: "SGD", countryCode: "SG" },
  { title: "Slovakia", phoneCode: "+421", currencyCode: "EUR", countryCode: "SK" },
  { title: "Slovenia", phoneCode: "+386", currencyCode: "EUR", countryCode: "SI" },
  { title: "Solomon Islands", phoneCode: "+677", currencyCode: "SBD", countryCode: "SB" },
  { title: "Somalia", phoneCode: "+252", currencyCode: "SOS", countryCode: "SO" },
  { title: "South Africa", phoneCode: "+27", currencyCode: "ZAR", countryCode: "ZA" },
  { title: "South Korea", phoneCode: "+82", currencyCode: "KRW", countryCode: "KR" },
  { title: "South Sudan", phoneCode: "+211", currencyCode: "SSP", countryCode: "SS" },
  { title: "Spain", phoneCode: "+34", currencyCode: "EUR", countryCode: "ES" },
  { title: "Sri Lanka", phoneCode: "+94", currencyCode: "LKR", countryCode: "LK" },
  { title: "Sudan", phoneCode: "+249", currencyCode: "SDG", countryCode: "SD" },
  { title: "Suriname", phoneCode: "+597", currencyCode: "SRD", countryCode: "SR" },
  { title: "Sweden", phoneCode: "+46", currencyCode: "SEK", countryCode: "SE" },
  { title: "Switzerland", phoneCode: "+41", currencyCode: "CHF", countryCode: "CH" },
  { title: "Syria", phoneCode: "+963", currencyCode: "SYP", countryCode: "SY" },
  { title: "Taiwan", phoneCode: "+886", currencyCode: "TWD", countryCode: "TW" },
  { title: "Tajikistan", phoneCode: "+992", currencyCode: "TJS", countryCode: "TJ" },
  { title: "Tanzania", phoneCode: "+255", currencyCode: "TZS", countryCode: "TZ" },
  { title: "Thailand", phoneCode: "+66", currencyCode: "THB", countryCode: "TH" },
  { title: "Timor-Leste", phoneCode: "+670", currencyCode: "USD", countryCode: "TL" },
  { title: "Togo", phoneCode: "+228", currencyCode: "XOF", countryCode: "TG" },
  { title: "Tonga", phoneCode: "+676", currencyCode: "TOP", countryCode: "TO" },
  { title: "Trinidad and Tobago", phoneCode: "+1-868", currencyCode: "TTD", countryCode: "TT" },
  { title: "Tunisia", phoneCode: "+216", currencyCode: "TND", countryCode: "TN" },
  { title: "Turkey", phoneCode: "+90", currencyCode: "TRY", countryCode: "TR" },
  { title: "Turkmenistan", phoneCode: "+993", currencyCode: "TMT", countryCode: "TM" },
  { title: "Tuvalu", phoneCode: "+688", currencyCode: "AUD", countryCode: "TV" },
  { title: "Uganda", phoneCode: "+256", currencyCode: "UGX", countryCode: "UG" },
  { title: "Ukraine", phoneCode: "+380", currencyCode: "UAH", countryCode: "UA" },
  { title: "United Arab Emirates", phoneCode: "+971", currencyCode: "AED", countryCode: "AE" },
  { title: "United Kingdom", phoneCode: "+44", currencyCode: "GBP", countryCode: "GB" },
  { title: "United States", phoneCode: "+1", currencyCode: "USD", countryCode: "US" },
  { title: "Uruguay", phoneCode: "+598", currencyCode: "UYU", countryCode: "UY" },
  { title: "Uzbekistan", phoneCode: "+998", currencyCode: "UZS", countryCode: "UZ" },
  { title: "Vanuatu", phoneCode: "+678", currencyCode: "VUV", countryCode: "VU" },
  { title: "Vatican City", phoneCode: "+379", currencyCode: "EUR", countryCode: "VA" },
  { title: "Venezuela", phoneCode: "+58", currencyCode: "VES", countryCode: "VE" },
  { title: "Vietnam", phoneCode: "+84", currencyCode: "VND", countryCode: "VN" },
  { title: "Yemen", phoneCode: "+967", currencyCode: "YER", countryCode: "YE" },
  { title: "Zambia", phoneCode: "+260", currencyCode: "ZMW", countryCode: "ZM" },
  { title: "Zimbabwe", phoneCode: "+263", currencyCode: "ZWL", countryCode: "ZW" },
];
